### ISSUE TITLE
Kelime Oyunu

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#10]

**Comment by temelt** [comment]
![img_3095](https://cloud.githubusercontent.com/assets/10330077/12548179/364afa40-c35d-11e5-915e-a2f9ee5fee27.JPG)

**Comment by seflek** [comment]
c321951 

hepsi tamam ama tekrarsız rastgele seçim sorununu çözemedim.

**Comment by atilganurdan** [comment]
d2d6efa

**Comment by KeremAdiguzel** [comment]
https://github.com/temelt/HSJProje/commit/9c031be5e0aded62bcd21f0041acab291ab6e1b8
