### ISSUE TITLE
Girilen Kelimeyi Mors alfabesine çevirme

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#11]
Girilen Kelimeyi Mors alfabesine çeviren metodu yazınız 
Mors alfabesi için aşağıdaki linki inceleyebilirsiniz.
http://www.mors.gen.tr/mors/content/ogrenim

**Comment by seflek** [comment]
bef0d4e

**Comment by seflek** [comment]
2c75466

**Comment by atilganurdan** [comment]
81ff34d
