### ISSUE TITLE
Şifreleme Algoritması

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#12]
Girilen bir metni basitçe şifrelemek için her bir karakterin ACSI değeri tek sayı ise 3 arttıran çift ise 2 azaltan bir algoritma olarak düşünebilirsiniz.

**Comment by temelt** [comment]
![ascii](https://cloud.githubusercontent.com/assets/10330077/12548276/d8718a64-c35d-11e5-89f5-37e645e7a5cd.jpeg)

**Comment by atilganurdan** [comment]
b7ecd00
