### ISSUE TITLE
Sayıları Yazıya çeviren Metod

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#4]
1 000 000 a kadar olan sayıları Yazıya çeviren Metod Yazılacak

**Comment by temelt** [comment]
https://github.com/temelt/HSJProje/commit/fb6d8cf7a6daf168105b3f735ae25b082243549d

**Comment by seflek** [comment]
HSJProje/HSJProje/src/com/vektorel/hsjp/main/seflek/SayiyiYaziyaCevirenProgram.java

**Comment by seflek** [comment]
c8d4dd2

**Comment by seflek** [comment]
c8d4dd2

**Comment by seflek** [comment]
https://github.com/temelt/HSJProje/blob/c8d4dd268ecb4714041a0e56c2f6ea1d570dab34/HSJProje/src/com/vektorel/hsjp/main/seflek/SayiyiYaziyaCevirenProgram.java

**Comment by atilganurdan** [comment]
bd303d3
