### ISSUE TITLE
Sayı Tahmin oyunu

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#5]
0 - 100 aralığında üretilen RANDOM sayının kullanıcıya buldurulması
Random sayı oluşturulması kodu aşağıdaki gibidir.

Random random = new Random(); 
int rasgeleOlusturulanSayi  = random.nextInt(100); 

Örnek : sayı 45 olsun ,

Kullanıcı girişi alınacak : 
Kullanıcı 25 girdi 
Kullanıcıya daha büyük bir tahminde bulununuz. mesajı verilmelidir
Kullanıcı 48 girdi 
Kullanıcıya daha küçük bir tahminde bulununuz. mesajı verilmelidir.
Kullanıcı 45 girdi
Doğru tahmini Buldunuz 
Mesajı verip tekrar oynamak istiyor musunuz? E/H
sorusu sorulacak ve H girildiğinde uygulama kapanmalıdır. E girildiginde tekrar başa dönüp tekrar random sayı üretilmelidir.

**Comment by damlatulek** [comment]
https://github.com/temelt/HSJProje/blob/master/HSJProje/src/com/vektorel/hsjp/main/damlatulek/Tahmin.java

**Comment by damlatulek** [comment]
https://github.com/temelt/HSJProje/blob/master/HSJProje/src/com/vektorel/hsjp/main/damlatulek/Tahmin.java

**Comment by patateskafa** [comment]
https://github.com/temelt/HSJProje/blob/master/HSJProje/src/com/vektorel/hsjp/main/patateskafa/SayiTahminOyunu.java

sorunsuz çalışıyor. fakat iki sıkıntı var:
1- 2 tane do-while ile yapmaktan daha kolay bir yolu olmalı? içim rahat
değil.
2- metodlara ayırarak yapmaya çalıştım fakat beceremedim.
hatta 3- nextLine sıkıntı çıkartıyor (derste biraz bahsetmiştiniz bundan) o yüzden next() ile aldım bir tane kullanıcı girdisini.

**Comment by atilganurdan** [comment]
ae0e24c

**Comment by seflek** [comment]
0e4395f
