### ISSUE TITLE
Ekrana Yıldız Yazdırma 

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#6]
Aşağıdaki Çıktıları üreten metodları for döngüsü ve if-else kullanarak gerçekleştiriniz

Örnek 1; 6X6 Matris
 *******************            
 *******************             
 *******************            
 *******************              
 *******************                  
 *******************                                   

Örnek 2;

*             
**             
***            
****            
*****           
******              
*******          

Örnek 3:

*      
**        
***             
****            
*****         
******        
*******         
******          
*****          
****          
***        
**         
*        

Örnek 4:

       *                          1 tane
      ***                         3 tane
     *****                       5 tane
      ***                         3 tane
       *                          1 tane

**Comment by atilganurdan** [comment]
4bafdcb

**Comment by KeremAdiguzel** [comment]
HSJProje/HSJProje/src/com/vektorel/hsjp/main/keremadiguzel/YildizYazanMetodlar.java
