### ISSUE TITLE
Fibbonacci Dizisi

### ISSUE THREAD

**Issue by temelt** [temelt/HSJProje#7]
1 000 000 dan küçük fibbonacci dizisini ekrana yazdıran metod

**Comment by damlatulek** [comment]
https://github.com/temelt/HSJProje/blob/master/HSJProje/src/com/vektorel/hsjp/main/damlatulek/Fibonacci.java

**Comment by atilganurdan** [comment]
800a0c3

**Comment by melisceylan** [comment]
9447941

**Comment by seflek** [comment]
https://github.com/temelt/HSJProje/blob/a022ee310ba6043ed5de8277d07ceed705055a8e/HSJProje/src/com/vektorel/hsjp/main/seflek/FibonacciSerisi.java
